### ISSUE TITLE
 It does not work on port 80

### ISSUE THREAD

**Issue by blavka** [bigclownlabs/bc-hub#8]
Change -p 8080:8080 to -p 80:8080 and open http://192.168.3.110:80 redirect me to http://192.168.3.110:8080/dashboard

**Comment by jirutka** [comment]
This is for purpose, to be consistent across all platforms and don't require root privileges on macOS to bind the port. Ask Michal if you want to know more.

**Comment by muhlpachr** [comment]
What is more, KISS or bad user input resilience ?
@hubpav can you comment on this please ?
We can easily support both ports with slightly more complicated configuration knowing 80 will not work on masOS without root priviledge.
Either -p 8080:8080 -p 80:8080 together or forward 80 to HTTP redirect.

**Comment by hubpav** [comment]
I suggest to stick with 8080 for the moment being. Even though it is a bit annoying. If we make our way through SSH tunneling, it will be a different story, ...again :-)

**Comment by blavka** [comment]
Ok, so delete tip from readme about change port.

**Comment by muhlpachr** [comment]
ok 8080 for now
